### PR TITLE
Update all tabs on first load

### PR DESCRIPTION
**Pull request by MikkCZ**
## Description and issue
At this moment when the extension is loaded (update from AMO, reload from `about:debugging`), it does not check the existing tabs.
### List of significant changes made
-  check the existing tabs on first background script load

### CODE REVIEW

**Comment by MikkCZ** [comment]
@shgysk8zer0 r?

**Comment by shgysk8zer0** [comment]
I was leaning towards not scanning all tabs on reload/install/update. For typical users, that wouldn't affect performance on startup too much. But it would likely be at least noticeable if a large number of tabs are open.

I think the better approach would be to:
1. Scan active tabs
2. Wait until any tabs are active to scan

I'll merge this and open an issue to setup some sort of queue.
Thanks!

**Comment by shgysk8zer0** [comment]
By the way, @MikkCZ , "r?"

Would you like to be listed as a contributor?

**Comment by MikkCZ** [comment]
You can list me, but it's not necessary. Keeping my name in the commit history is perfectly OK for me. :)

**Pull request merged**
