### PR TITLE
Allow much more customization

### PR DESCRIPTION
**Pull request by shgysk8zer0**
- Allow setting color and font size & family
- Allow selecting template to use
- Allow setting background color & image
- Allow setting padding & margins
- Set styles using CSS custom properties
- Update default options
- Add update script

### CODE REVIEW

**Comment by Keith94** [comment]
Will this allow the popup to look and feel more closely to the native popups? Like so

**Comment by shgysk8zer0** [comment]
@Keith94 It will allow extensive control over a lot of styles. I think I'll have to add margins to get that exact style.
Would you happen to know where the CSS is for that popup?

Current settings look like this:
screeshot

**Comment by shgysk8zer0** [comment]
An example of what is possible:
- screenshot
- screenshot-20170926220158-341x190
- screenshot

Current options:
screenshot-20170926220350-1181x476

**Comment by Keith94** [comment]
I think the photon panel stuff is contained in this file, but I could be wrong:
https://github.com/mozilla/gecko-dev/blob/master/browser/themes/shared/customizableui/panelUI.inc.css#L398

I'd prefer something as native as possible by default, but extra customization is always good too ;)

**Comment by shgysk8zer0** [comment]
@Keith94 I got it as close to native as I reasonably could. I can say that it looks almost indistinguishable on my computer, but that's Firefix Dev on Fedora. Results may vary on different OSs.

screenshot from 2017-09-27 01-28-28

screenshot from 2017-09-27 01-28-38

**Pull request merged**
